- title: Characteristic expression of major histocompatibility complex and immune privilege genes in human pluripotent stem cells and their derivatives
  remove: true

- title: Eye anomalies and neurological manifestations in patients with PAX6 mutations.
  remove: true

- title: Tandem mass neonatal screening in Taiwan - Report from one center
  remove: true

- title: Viral infections and prolonged fever after liver transplantation in young children with inborn errors of metabolism
  remove: true

- title: "Kawasaki disease associated with chickenpox: Report of two sibling cases"
  remove: true
  
- title: Transcription factors involved in pancreatic islet development
  remove: true

- title: Diabetes, defective pancreatic morphogenesis, and abnormal enteroendocrine differentiation in BETA2/NeuroD-deficient mice
  remove: true
  
- title: BETA3, a novel helix-loop-helix protein, can act as a negative regulator of BETA2 and MyoD-responsive genes
  remove: true